--Tipo de Habitacion
insert into TipoHabitacion values ('Semiprivada', 900)
insert into TipoHabitacion values ('Privada', 1500)
insert into TipoHabitacion values ('Suite', 2000)
--Especualidad medica
insert into EspecialidadMedica (Descripcion) values ('Cardiólogo')
insert into EspecialidadMedica (Descripcion) values ('Cirugia General')
insert into EspecialidadMedica (Descripcion) values ('Cirugia Plastica')
insert into EspecialidadMedica (Descripcion) values ('Dermatología')
insert into EspecialidadMedica (Descripcion) values ('Ginecología')
insert into EspecialidadMedica (Descripcion) values ('Medicina Interna')
insert into EspecialidadMedica (Descripcion) values ('Oftalmología')
insert into EspecialidadMedica (Descripcion) values ('Oncología')
insert into EspecialidadMedica (Descripcion) values ('Pediatría')
insert into EspecialidadMedica (Descripcion) values ('Psiquiatría')
insert into EspecialidadMedica (Descripcion) values ('Traumatología')
insert into EspecialidadMedica (Descripcion) values ('Urología')
insert into EspecialidadMedica (Descripcion) values ('Enfermería')
--Tipo Atenciones
insert into TipoAtencion (Descripcion) values ('Mayor')
insert into TipoAtencion (Descripcion) values ('Menor')
insert into TipoAtencion (Descripcion) values ('Cirugía de mínimo acceso')
insert into TipoAtencion (Descripcion) values ('Cirugía Neonatal')
insert into TipoAtencion (Descripcion) values ('Dermatología')
insert into TipoAtencion (Descripcion) values ('Neuroendesopía')
insert into TipoAtencion (Descripcion) values ('Glaucoma')
insert into TipoAtencion (Descripcion) values ('Oculoplastía')
insert into TipoAtencion (Descripcion) values ('Cornea')
insert into TipoAtencion (Descripcion) values ('Implanto Refractiva')
--Tipo Articulo
insert into TipoArticulo values ('Equipo de Bioseguridad')
insert into TipoArticulo values ('Herramientas')
insert into TipoArticulo values ('Materiales')
insert into TipoArticulo values ('Limpieza')
insert into TipoArticulo values ('Otros')
--Inventario
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Jabón', 4, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Aguja', 3, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Cateter', 3, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Sonda', 3, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Gasa', 3, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Algodon', 3, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Guante', 1, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Gafas', 1, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Careta', 1, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Jeringa', 3, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Batas', 1, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Traje Biológico', 1, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Hilo', 3, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Protector Zapatos', 1, 50)
insert into Inventario (Descripcion, TipoArticuloID, Cantidad) values ('Bolsa desechos biológicos', 5, 50)
--Habitaciones
insert into Habitacion values (1, 1, 1, 'L')
insert into Habitacion values (1, 2, 1, 'L')
insert into Habitacion values (1, 3, 1, 'L')
insert into Habitacion values (2, 1, 1, 'L')
insert into Habitacion values (2, 2, 1, 'L')
insert into Habitacion values (2, 3, 1, 'L')
insert into Habitacion values (3, 1, 1, 'L')
insert into Habitacion values (3, 2, 1, 'L')
insert into Habitacion values (3, 3, 1, 'L')
insert into Habitacion values (4, 1, 1, 'L')
insert into Habitacion values (4, 2, 1, 'L')
insert into Habitacion values (4, 3, 1, 'L')
insert into Habitacion values (5, 1, 2, 'L')
insert into Habitacion values (6, 1, 2, 'L')
insert into Habitacion values (7, 1, 2, 'L')
insert into Habitacion values (8, 1, 2, 'L')
insert into Habitacion values (9, 1, 3, 'L')
insert into Habitacion values (10, 1, 3, 'L')
insert into Habitacion values (11, 1, 3, 'L')
insert into Habitacion values (12, 1, 3, 'L')






